(()=>{'use strict';
const MONTHS=['Jänner','Februar','März','April','Mai','Juni','Juli','August','September','Oktober','November','Dezember'];
const CATEGORIES=['Montage','Lieferung','Produktion','Inbetriebnahme','Abnahme','Service','Urlaub','Krank','Feiertag','Besprechung','Wartung','Sonstiges'];
const cfg=window.APP_CONFIG||{}, key=cfg.SUPABASE_PUBLISHABLE_KEY||'';
const live=Boolean(cfg.SUPABASE_URL&&key&&window.supabase), client=live?window.supabase.createClient(cfg.SUPABASE_URL,key):null;
const state={year:new Date().getFullYear(),entries:[],channel:null,searchIndex:0}; const $=id=>document.getElementById(id);
const iso=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const parse=v=>{const [y,m,d]=v.split('-').map(Number);return new Date(y,m-1,d)};
const norm=v=>String(v||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]/g,'');
const cls=v=>`cat-${norm(v)}`; const esc=v=>String(v||'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function week(d){const x=new Date(Date.UTC(d.getFullYear(),d.getMonth(),d.getDate()));const day=x.getUTCDay()||7;x.setUTCDate(x.getUTCDate()+4-day);const y=new Date(Date.UTC(x.getUTCFullYear(),0,1));return Math.ceil((((x-y)/86400000)+1)/7)}
function overlap(e,d){const t=iso(d);return e.start_date<=t&&e.end_date>=t}
function filtered(){const q=norm($('searchInput').value),cat=$('categoryFilter').value;return state.entries.filter(e=>(!q||norm([e.title,e.project_number,e.notes,e.category].join(' ')).includes(q))&&(!cat||e.category===cat))}
function setup(){CATEGORIES.forEach(c=>{$('categoryFilter').add(new Option(c,c));$('entryCategory').add(new Option(c,c));const s=document.createElement('span');s.innerHTML=`<i class="dot ${cls(c)}"></i>${c}`;$('legend').appendChild(s)});const y=new Date().getFullYear();for(let i=y-5;i<=y+8;i++)$('yearSelect').add(new Option(i,i));$('yearSelect').value=state.year}
function monthNav(){const n=$('monthNav');n.innerHTML='';$('sidebarYear').textContent=state.year;MONTHS.forEach((m,i)=>{const b=document.createElement('button');b.textContent=m;b.onclick=()=>document.getElementById(`month-${i}`)?.scrollIntoView({behavior:'smooth'});n.appendChild(b)})}
function formatDate(value){if(!value)return '';const d=parse(value);return d.toLocaleDateString('de-AT',{day:'2-digit',month:'2-digit',year:'numeric'})}
function jumpToEntry(entry){const start=parse(entry.start_date);if(start.getFullYear()!==state.year){state.year=start.getFullYear();$('yearSelect').value=state.year;render()}requestAnimationFrame(()=>{const target=document.querySelector(`[data-date="${entry.start_date}"]`)||document.getElementById(`month-${start.getMonth()}`);target?.scrollIntoView({behavior:'smooth',block:'center'});if(target?.classList.contains('day')){target.classList.add('search-hit');setTimeout(()=>target.classList.remove('search-hit'),1800)}})}
function renderResults(es){const active=$('searchInput').value.trim()||$('categoryFilter').value;const box=$('searchResults');box.classList.toggle('hidden',!active);if(!active){box.innerHTML='';state.searchIndex=0;return}if(!es.length){box.innerHTML='<div class="search-empty">Keine passenden Termine gefunden.</div>';state.searchIndex=0;return}state.searchIndex=Math.min(state.searchIndex,es.length-1);const current=es[state.searchIndex];box.innerHTML=`<div class="search-nav"><button type="button" id="prevSearchResult" class="icon-btn" aria-label="Vorheriger Treffer">‹</button><div class="search-result-summary"><strong>${state.searchIndex+1} / ${es.length}</strong><span>${esc(current.project_number?current.project_number+' – ':'')}${esc(current.title)}</span><small>${esc(current.category)} · ${formatDate(current.start_date)}${current.end_date!==current.start_date?' bis '+formatDate(current.end_date):''}</small></div><button type="button" id="nextSearchResult" class="icon-btn" aria-label="Nächster Treffer">›</button></div>`;$('prevSearchResult').onclick=()=>{state.searchIndex=(state.searchIndex-1+es.length)%es.length;renderResults(es);jumpToEntry(es[state.searchIndex])};$('nextSearchResult').onclick=()=>{state.searchIndex=(state.searchIndex+1)%es.length;renderResults(es);jumpToEntry(es[state.searchIndex])}}
function render(){monthNav();const es=filtered();renderResults(es);$('calendar').innerHTML='';const tpl=$('monthTemplate'),today=iso(new Date());MONTHS.forEach((name,mi)=>{const card=tpl.content.firstElementChild.cloneNode(true);card.id=`month-${mi}`;card.querySelector('h2').textContent=name;const me=es.filter(e=>overlap(e,new Date(state.year,mi,1))||overlap(e,new Date(state.year,mi+1,0))||(e.start_date<iso(new Date(state.year,mi,1))&&e.end_date>iso(new Date(state.year,mi+1,0))));card.querySelector('.month-count').textContent=`${me.length} Termin${me.length===1?'':'e'}`;const days=card.querySelector('.days'),first=new Date(state.year,mi,1),offset=(first.getDay()+6)%7,start=new Date(state.year,mi,1-offset);for(let r=0;r<6;r++){const monday=new Date(start);monday.setDate(start.getDate()+r*7);const kw=document.createElement('div');kw.className='week-number';kw.textContent=week(monday);days.appendChild(kw);for(let c=0;c<7;c++){const d=new Date(start);d.setDate(start.getDate()+r*7+c);const cell=document.createElement('div');cell.className='day';cell.dataset.date=iso(d);if(d.getMonth()!==mi)cell.classList.add('outside');if(iso(d)===today)cell.classList.add('today');cell.innerHTML=`<span class="day-number">${d.getDate()}</span><div class="events"></div>`;const de=es.filter(e=>overlap(e,d));de.slice(0,3).forEach(e=>{const b=document.createElement('button');b.className=`event ${cls(e.category)}`;b.textContent=`${e.project_number?e.project_number+' – ':''}${e.title}`;b.title=`${e.category}: ${e.title}${e.notes?'\n'+e.notes:''}`;b.onclick=()=>openEntry(e);cell.querySelector('.events').appendChild(b)});if(de.length>3){const m=document.createElement('div');m.className='more';m.textContent=`+${de.length-3} weitere`;cell.querySelector('.events').appendChild(m)}cell.ondblclick=()=>openEntry(null,iso(d));days.appendChild(cell)}}$('calendar').appendChild(card)})}
async function load(){if(!live){state.entries=JSON.parse(localStorage.getItem('mad_company_calendar')||'[]');$('modeBadge').textContent='Lokal';render();return}const {data,error}=await client.from('company_calendar_entries').select('*').order('start_date');if(error){$('modeBadge').textContent='Fehler';console.error(error);alert('Supabase-Tabelle fehlt oder ist noch nicht freigegeben. Bitte SQL-Update ausführen.');return}state.entries=data||[];$('modeBadge').textContent='Online';render()}
function openEntry(e=null,date=null){$('entryForm').reset();$('entryId').value=e?.id||'';$('entryDialogTitle').textContent=e?'Termin bearbeiten':'Termin eintragen';$('entryCategory').value=e?.category||'Montage';$('entryTitle').value=e?.title||'';$('entryStart').value=e?.start_date||date||iso(new Date());$('entryEnd').value=e?.end_date||date||iso(new Date());$('entryProjectNumber').value=e?.project_number||'';$('entryNotes').value=e?.notes||'';$('deleteEntryBtn').classList.toggle('hidden',!e);$('entryDialog').showModal()}
async function save(ev){ev.preventDefault();const id=$('entryId').value,p={category:$('entryCategory').value,title:$('entryTitle').value.trim(),start_date:$('entryStart').value,end_date:$('entryEnd').value,project_number:$('entryProjectNumber').value.trim(),notes:$('entryNotes').value.trim()};if(p.end_date<p.start_date)return alert('Das Enddatum darf nicht vor dem Startdatum liegen.');if(!live){if(id)state.entries=state.entries.map(e=>e.id===id?{...e,...p}:e);else state.entries.push({id:crypto.randomUUID(),...p});localStorage.setItem('mad_company_calendar',JSON.stringify(state.entries));$('entryDialog').close();render();return}const {error}=id?await client.from('company_calendar_entries').update(p).eq('id',id):await client.from('company_calendar_entries').insert(p);if(error)return alert(error.message);$('entryDialog').close();await load()}
async function del(){const id=$('entryId').value;if(!id||!confirm('Termin wirklich löschen?'))return;if(!live){state.entries=state.entries.filter(e=>e.id!==id);localStorage.setItem('mad_company_calendar',JSON.stringify(state.entries));$('entryDialog').close();render();return}const {error}=await client.from('company_calendar_entries').delete().eq('id',id);if(error)return alert(error.message);$('entryDialog').close();await load()}
function jumpToday(){const d=new Date();state.year=d.getFullYear();$('yearSelect').value=state.year;render();requestAnimationFrame(()=>document.querySelector(`[data-date="${iso(d)}"]`)?.scrollIntoView({behavior:'smooth',block:'center'}))}
function bind(){$('prevYearBtn').onclick=()=>{state.year--;$('yearSelect').value=state.year;render()};$('nextYearBtn').onclick=()=>{state.year++;$('yearSelect').value=state.year;render()};$('yearSelect').onchange=()=>{state.year=+$('yearSelect').value;render()};$('todayBtn').onclick=jumpToday;$('newEntryBtn').onclick=()=>openEntry();$('searchInput').oninput=()=>{state.searchIndex=0;render();const es=filtered();if($('searchInput').value.trim()&&es.length)jumpToEntry(es[0])};$('searchInput').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();const es=filtered();if(es.length)jumpToEntry(es[state.searchIndex]||es[0])}};$('categoryFilter').onchange=render;$('clearFiltersBtn').onclick=()=>{$('searchInput').value='';$('categoryFilter').value='';render()};$('entryForm').onsubmit=save;$('deleteEntryBtn').onclick=del;$('closeEntryDialog').onclick=$('cancelEntryBtn').onclick=()=>$('entryDialog').close()}
async function init(){setup();bind();render();await load();if(live)state.channel=client.channel('company-calendar-live').on('postgres_changes',{event:'*',schema:'public',table:'company_calendar_entries'},load).subscribe()}
init();})();
